apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: ravidsinghbiz
    provider: github
    repository: skiapp
  name: ravidsinghbiz-skiapp
spec:
  description: Imported application for ravidsinghbiz/skiapp
  httpCloneURL: https://github.com/ravidsinghbiz/skiapp.git
  org: ravidsinghbiz
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: skiapp
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/ravidsinghbiz/skiapp.git
